swagger: "2.0"

info:
  title: Moku Moku Cards & Decks API
  description: Flash cards learning platform's Cards & Decks CRUD micro-service API documention.
  version: 1.0.0

consumes:
  - application/json
produces:
  - application/json

definitions:
  Card:
    type: object
    properties:
      id:
        type: string
      front:
        type: string
      back:
        type: string
      image:
        type: string

  Deck:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      cards:
        type: array
        items:
          type: integer
          format: int64

  RestErr:
    type: object
    properties:
      message:
        type: string
      status:
        type: integer
        format: int
      error:
        type: string

parameters:
  access_token:
    name: access_token
    type: integer
    in: header
    required: true